#!/usr/bin/env python
"""
Description:
    Personal gadget interface.

Usage:
    gadget play-dic <voice>
    gadget load-mp3 <mp3File>

Options:
    -h --help   Extensive help message.
"""

from subprocess import call, PIPE
from docopt import docopt
import os
import shutil

if __name__ == '__main__':
    args = docopt(__doc__)

    if args['play-dic']:

        voicesPath = os.path.join('/media', os.environ.get('USER'), 'DVT1100/VOICE', args['<voice>'])
        trashPath = os.path.join('/home', os.environ.get('USER'), '.local/share/Trash')

        voices = os.listdir(voicesPath)
        for file in voices:
            filePath = os.path.join(voicesPath, file)
            print(filePath)
            call('audacity ' + filePath + ' > /dev/null 2>&1', shell=True)

            if 'y' == raw_input('Remove ' + file + ' (y/n):'):
                trashFilePath = os.path.join(trashPath, file)
                try:
                    shutil.move(filePath, trashFilePath)
                except OSError:
                    os.rename(filePath, trashFilePath)

    elif args['load-mp3']:
        print(os.path.join(os.getcwd(), args['<mp3File>']))
