#!/usr/bin/env python
"""
Description:
    Linux post installation helper.

Usage:
    linux install
    linux config
    linux report

Options:
    -h --help   Extensive help message.
"""

try:
    from subprocess import call
    from docopt import docopt
    from libs import aptInstall, aptReport, config, pipInstall,pipReport,npmInstall
    from apt.cache import LockFailedException

    if __name__ == '__main__':
        args = docopt(__doc__)
        if args['install']:
            aptInstall()
            pipInstall()
            npmInstall()
            aptReport()
            pipReport()

        elif args['report']:
            aptReport()
            pipReport()

        elif args['config']:
            config()

except KeyError as err:
    print('ERROR: ' + err.message)

except ImportError as err:
    print('ERROR: ' + err.message)
    if 'y'== raw_input('Do you want setup linux? (y/n): '):
        call("./config/scripts/setup.sh".split())