#!/usr/bin/env bash

xrandr --output VGA-1 --off --output eDP-1 --off --output LVDS-1 --off --output DP-3 --mode 3840x2160 --pos 2160x0 --rotate left --output DP-2 --primary --mode 3840x2160 --pos 0x0 --rotate left --output DP-1 --off

nohup slack </dev/null >/dev/null 2>&1 & # completely detached from terminal
nohup chromium-browser http://awakeningbell.org/ https://www.youtube.com/watch?v=ddFvjfvPnqk https://www.internet-radio.com/station/veniceclassicradio/ </dev/null >/dev/null 2>&1 & # completely detached from terminal
nohup pycharm </dev/null >/dev/null 2>&1 & # completely detached from terminal

exit
