#!/usr/bin/env bash

xrandr --output VGA-1 --off --output eDP-1 --off --output LVDS-1 --off --output DP-3 --mode 3840x2160 --pos 3840x0 --rotate left --output DP-2 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-1 --off

nohup slack > /dev/null 2>&1&
nohup chromium-browser --new-window > /dev/null 2>&1&
nohup chromium-browser --new-window https://www.youtube.com/channel/UCUPn5IEQugMf_JeNJOV9p2A > /dev/null 2>&1&
nohup pycharm </dev/null > /dev/null 2>&1&

exit
