#!/usr/bin/env bash

xrandr --output VGA-1 --off --output eDP-1 --off --output LVDS-1 --off --output DP-3 --mode 3840x2160 --pos 2160x0 --rotate left --output DP-2 --primary --mode 3840x2160 --pos 0x0 --rotate left --output DP-1 --off

slack &&
chromium-browser --new-window https://www.youtube.com/watch?v=ddFvjfvPnqk &&
chromium-browser http://awakeningbell.org/ &&
pycharm &&

exit
