#!/usr/bin/env python
"""
Description:
    Personal gadget interface.

Usage:
    gadget dic play <voice>
    gadget mp3 load <mp3File>

Options:
    -h --help   Extensive help message.
"""

from subprocess import Popen, PIPE
from docopt import docopt
import os
import json

gadgets = {
    "dict": {
        'uuid': "0000-006F",
        'alias': 'dictaphone'
    },
    'mp3': {
        'uuid': "846D-FD0B",
        'alias': 'mp3player'
    }
}


def shell(command):
    output, err = Popen(command.split(), stdout=PIPE, stderr=PIPE).communicate()
    return output


def getMountPoint(*path):
    return os.path.join('/media', os.environ.get("USER"), *path)


def gadgetsMounter(unmount=False):
    lsblk = json.loads(
        shell('lsblk -f -J')
    )

    for device in lsblk['blockdevices']:
        for i in gadgets:
            gadget = gadgets[i]
            if gadget['uuid'] == device['uuid']:
                mountPoint = getMountPoint(gadget['alias'])

                if unmount:
                    shell('sudo unmount {} {}'.format(os.path.join('/dev', device['name']), mountPoint))
                    print('Un mount: ' + mountPoint)
                else:
                    shell('sudo mkdir -p {}'.format(mountPoint))
                    shell('sudo mount {} {}'.format(os.path.join('/dev', device['name']), mountPoint))
                    print('Mount: ' + mountPoint)


def getDriveFolder(*path):
    return os.path.join('/home', os.environ.get("USER"), 'gdrive', *path)


if __name__ == '__main__':

    args = docopt(__doc__)

    gadgetsMounter()

    if args['dic']:
        if args['play']:
            voicesPath = getMountPoint(gadgets['dict']['alias'], 'VOICE', args['<voice>'])

            voices = os.listdir(voicesPath)
            for file in voices:
                filePath = os.path.join(voicesPath, file)
                print(filePath)
                shell('vlc {} '.format(filePath))

                if 'y' == raw_input('Upload file (y/n):'):
                    emotion = raw_input('Custvo: ')
                    shell('cp {} {}', filePath, getDriveFolder(emotion))

                if 'y' == raw_input('Trash file (y/n):'):
                    shell('sudo gvfs-trash {}'.format(filePath))

    elif args['mp3']:
        if args['load']:
            print(os.path.join(os.getcwd(), args['<mp3File>']))
