#!/usr/bin/env bash

layout=$(setxkbmap -query | grep layout | awk '{print $2}')
if [ $layout = "us" ] ; then
    setxkbmap -layout si -option && xmodmap ~/.Xmodmap
else
    setxkbmap -layout us -option
fi

xmodmap ~/.Xmodmap
