#!/usr/bin/env python3
import subprocess
from time import sleep


def get(cmd): return subprocess.check_output(cmd).decode("utf-8")
def run(cmd): subprocess.call(["/bin/bash", "-c", cmd])

layout_current = None
while True:
    layout = get(['setxkbmap', '-query']).split()[-1][0]
    if layout_current != layout:
        layout_current = layout
        run(f'spd-say {layout}')
    sleep(0.1)
